### ISSUE TITLE
Building the MVP

### ISSUE THREAD

**Issue by hathix** [Harvard-Open-Data-Project/harvard-open-data-project.github.io#16]
Here we can discuss the technical details of building the minimum viable product.

For background reading, see the following threads:
- https://github.com/Harvard-Open-Data-Project/droid/issues/12
- https://github.com/Harvard-Open-Data-Project/droid/issues/4

**Comment by hathix** [comment]
What are we looking at building? A WordPress site with embedded Dataverse widgets (effectively a rebranded Dataverse) or a more full-featured site that talks to Dataverse under the hood while exposing a different interface?

Some undergrads are interested in getting started building an MVP this summer so the sooner we have an idea of what to build the better.

**Comment by jimwaldo** [comment]
I'd say that we already have an MVP-- take a look at https://dataverse.harvard.edu/dataverse/harvardopendata

Which is up, running, and even contains some APIs. While we might be able to build something that we like better with some combination of workpress and the like, this approach means that we don't need to find someone to run the result. Believe me, that is a HUGE advantage.

There are some things that we need to do before publishing this. Getting a better skin on the dataverse would be nice; someone working with the Dataverse team could get to work on this (bringing in the HPAC folks, as well). We will also need to construct a script that will check to make sure that APIs, especially, are still live; something that will go through the published APIs, collect the endpoints, call those endpoints, and report if there is no response. This will help to maintain the site; the problem with sites like this (which is why the Mass. open data site has been shut down) is that links get stale, data ceases to be updated, and things fall apart.

Then there is the question of getting and cataloging more data. The more data we can get and the better the descriptions, the more likely it is that people will come to the site. I'm in the process of getting the Harvard course catalog, but other data sources would be great to add.

**Comment by nsinai** [comment]
@hathix @jimwaldo -- I'd suggest we re-open this issue and continue this conversation.  At the most recent meet-up on this project, we attempted to enter a couple dozen data sets into Dataverse, and it became clear that it is really not designed to be a open data catalog (as opposed to data repository software).  @hathix -- can you give some specific examples here about the limitations of Dataverse?

I'd suggest we explore the use of CKAN again, as a service, hosted on AWS, or on Harvard infrastructure.
